In [34]:
import numpy as np

In [35]:
score = np.loadtxt("C:/DIPython/python_score.csv", delimiter=",", dtype="float64")

In [36]:
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

In [37]:
score1 = score[:19]
score1

array([[3., 3., 4., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 3., 4., 4., 2., 2., 4.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1.],
       [2., 2., 3., 2., 4., 2., 2., 4., 4., 2., 2.],
       [2., 4., 2., 4., 2., 2., 2., 2., 4., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 3., 4., 4., 2., 4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 2., 3., 3., 3., 3., 1., 3., 3., 3., 3.],
       [2., 2., 4., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 1., 1., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2.],
       [2., 2., 4., 2., 2., 2., 2., 2., 2., 2.

In [38]:
answer = [d[10] for d in score1]
answer = np.array(answer)
answer

array([3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2., 1.,
       2., 2.])

In [39]:
dset = score1[:, :10]
dset = dset.T
dset

array([[3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 3., 3., 3., 2., 2., 2.,
        1., 2., 2.],
       [4., 4., 1., 1., 3., 2., 1., 4., 4., 2., 4., 3., 3., 3., 4., 2.,
        1., 2., 4.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 4., 2., 3., 3., 2., 1.,
        1., 2., 2.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 2., 3., 3., 3., 2., 1.,
        1., 2., 2.],
       [3., 3., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2.],
       [3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 1., 2., 2.,
        1., 2., 2.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2.],
       [3., 2., 1., 2., 4., 4., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        2., 4., 2.],
       [3., 2., 1., 1., 2., 2., 1., 4., 2., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2.]])

In [40]:
bool_dset1 = (dset == answer)
bool_dset1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  T

In [47]:
bool_dset2 = bool_dset1.astype(float)
bool_dset2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
        1., 1., 1.],
       [0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        1., 1., 0.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
        1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]])

## 객관식 점수 계산

In [48]:
score1_array = np.ones(19)
score1_array = score1_array * 4
score1_array

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4.])

In [51]:
objective_score = np.dot(bool_dset2, score1_array)
objective_score

array([76., 64., 60., 64., 64., 72., 72., 72., 52., 68.])

## 주관식 점수 계산

In [52]:
dset2 = score[20:, :10]    
dset2

array([[ 9.,  4., 10.,  9.,  6.,  8., 10.,  7.,  6.,  9.],
       [ 5.,  7.,  8.,  5.,  7.,  8.,  6.,  8.,  9., 10.]])

In [53]:
dset3 = dset2[0]
dset3 

array([ 9.,  4., 10.,  9.,  6.,  8., 10.,  7.,  6.,  9.])

In [54]:
dset4 = dset2[1]
dset4

array([ 5.,  7.,  8.,  5.,  7.,  8.,  6.,  8.,  9., 10.])

In [55]:
subjective_score = dset3 + dset4
subjective_score

array([14., 11., 18., 14., 13., 16., 16., 15., 15., 19.])

# 총점구하기

In [56]:
Total_score = objective_score + subjective_score
Total_score

array([90., 75., 78., 78., 77., 88., 88., 87., 67., 87.])